#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define ENEMY_SPAWN_FREQUENCY 0.002
#define MONEY_SPAWN_FREQUENCY 1

#define MOUNT_MOVEMENT_SPEED 0.01
#define CLOUD_MOVEMENT_SPEED 0.008
#define MBIRD_MOVEMENT_SPEED 0.003
#define MONEY_MOVEMENT_SPEED 0.005

#define OBSTACLE_COLLISION_BITMASK 0x000002

#define BIRD_FALLING_SPEED 0.0025
#define BIRD_FLYING_SPEED 0.00375
#define BIRD_FLY_DURATION 0.25

#define SCORE_FONT_SIZE 0.1

#define MONEY_TAG 98
#define ENEMY_TAG 99
#define PLAYER_TAG 100

#define INTERACTION_FORCE 12000
#define WORLD_GRAVITY 500
#define PLAYER_MASS 100
#define PACKAGE_MASS 100


#define JOINT_AMOUNT 6

#endif // __DEFINITIONS_H__
